/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.MessageResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-10-17T03:25:42.567Z[GMT]")
@Api(value = "installed_application", description = "the installed_application API")
public interface InstalledApplicationApi {

    @ApiOperation(value = "Add iBeacon log and responce message", nickname = "addIBeaconReceivedInfo", notes = "", response = MessageResponse.class, tags={ "iBeacon", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = MessageResponse.class),
        @ApiResponse(code = 405, message = "Invalid input"),
        @ApiResponse(code = 404, message = "Installed Application not found"),
        @ApiResponse(code = 400, message = "Invalid ID supplied") })
    @RequestMapping(value = "/installed_application/ibeacon_received_info_log",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<MessageResponse> addIBeaconReceivedInfo(@ApiParam(value = ""  )  @Valid @RequestBody List<Object> body
);

}

