//
// MessageResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageResponse: Codable {

    public var message: MessageResponseMessage?

    public init(message: MessageResponseMessage?) {
        self.message = message
    }


}

