//
// MessageResponseMessage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MessageResponseMessage: Codable {

    public var title: String?
    public var body: String?

    public init(title: String?, body: String?) {
        self.title = title
        self.body = body
    }


}

